### ISSUE TITLE
clarify when pastes expire

### ISSUE THREAD

**Issue by vks** [dgl/paste.sh#1]
When using the website it is currently unclear when (or whether) the pastes will expire. It would be helpful to have a sentence about this at https://paste.sh/about.

**Comment by Flipmode11** [comment]
@vks Agreed. 
p.s. Your name is familiar... Do I know you _:D_

**Comment by nuflowx** [comment]
Wondering the same, no mention anywhere

**Comment by dgl** [comment]
Mostly they don't, but no guarantees obviously.
