### ISSUE TITLE
paste.sh is down?

### ISSUE THREAD

**Issue by itsrachelfish** [dgl/paste.sh#2]
I'm pretty sure this isn't really an issue with the code itself, but paste.sh is down.

Did something happen?

Did you get raided? xD

**Comment by dgl** [comment]
Sigh. It seems .sh is pretty shit and despite me having given them money they aren't renewing it for some reason.

**Comment by itsrachelfish** [comment]
@dgl Lame! paste.sh is my favorite pastebin site :(

**Comment by Flipmode11** [comment]
​Someone rip and copy it already!
Then we can register a domain (<$10) and host it (sorted).
_:(_

Paste.sh was kick ass!
