### ISSUE TITLE
Certificate for paste.sh has expired on July 16

### ISSUE THREAD

**Issue by 13xforever** [dgl/paste.sh#3]
Consider switching to Let's Encrypt and automating the renewal process.

**Comment by Flipmode11** [comment]
STEP-BY-STEP PROCESS?? Can someone write up how to do everything with Let's
Encrypt? I've been a registered member for over 1 year. Still not used it.
:(
Please help. Thanks guys.

**Comment by 13xforever** [comment]
There's a [documentation](https://letsencrypt.org/getting-started/) with step-by-step instrucitons, I haven't had any trouble rolling it out even when it was in private beta. It's even easier if you're using Apache or Nginx.

**Comment by dgl** [comment]
It's renewed for now, using let's encrypt needs some more work on my hosting side.

**Comment by Flipmode11** [comment]
YOU'RE A CHAMPION!
Thanks mate!

Sent via my Samsung Galaxy S2.
