### ISSUE TITLE
paste.sh website down

### ISSUE THREAD

**Issue by antoine1619** [dgl/paste.sh#6]
When I navigate to the paste.sh url, I get the following error: 
```
503 Service Unavailable
No server is available to handle this request. 
```
Is the website still being maintained? If so, can someone explain to a beginner how to self host paste.sh?

**Comment by irgendwatmitcomputer** [comment]
I also just wanted to open an issue. I actually stored some important information there temporarily which I now can't access. Hope the server is back up again soon - been using paste.sh for years now :-)

**Comment by dgl** [comment]
Sorry, back now.

**Comment by irgendwatmitcomputer** [comment]
Still down for me. Getting an HTTP 503

**Comment by irgendwatmitcomputer** [comment]
Working now - Thanks @dgl
