### ISSUE TITLE
how to set this up?

### ISSUE THREAD

**Issue by Alistair1231** [dgl/paste.sh#7]
Hi. I have issues hosting this myself.

1. It complains about Plack::Runner being missing, even though it tells me it's there when I run `cpanm -l deps Plack::Runner`
1.1 So I have to manually install it using `cpanm Plack::Runner`
1. Next it complains about `serverauth` being missing. 
2.1 So I created a file with that name and put some random string in there.
1. Now it starts, but when I open the url localhost:5000 it only returns `Not found`.

What am I doing wrong?
Thanks for the software btw. I really like it.

**Comment by killparty** [comment]
I love the simplicity and I'd like to host this myself. But I'm also clueless how to put this up

**Comment by dgl** [comment]
Hi, glad you like it.

Try editing the host in update-misc, then run `./update-misc`.

(There might be another couple of places which hardcode the host, although it may not need changing to work as it is used as part of the derived key, so will work either way, just better to update it.)
