### ISSUE TITLE
Bug: It fails to show pastes with special sequences

### ISSUE THREAD

**Issue by Drugoy** [dgl/paste.sh#9]
It fails to show pastes with special sequences.
Step to reproduce:
Try to share a paste with this code:
```
precmd_coloredexitcode() {
  exitcode="${?}"
  if [[ "${exitcode}" -eq 0 ]]; then
    COLOREDEXITCODE="$(printf '[%b%s%b]' '\033[0;32m' "OK" '\033[0m')"
  else
    COLOREDEXITCODE="$(printf '[%b%s%b: %d]' '\033[1;31m' 'ERR' '\033[0m' "${exitcode}")"
  fi
}

# that function is in precmd_functions array and variable COLOREDEXITCODE is in PROMPT
```
Expected result: the paste should treat all of that as literal text.
Actual result: opening the paste's URL in a new tab opens a page that says "Decryption failed (Error: Malformed UTF-8 data)"

**Comment by dgl** [comment]
Simple reproducer is: `printf "\xa3" | paste.sh`

Will be fixed shortly.

**Comment by dgl** [comment]
```
$ printf "\xa3" | paste.sh
Saved 44 bytes.
https://paste.sh/hq2HSZ1R#1iawUmBnIsC-1P3ZzvRaziel
```

Now does the expected thing (decodes as latin1 if UTF-8 fails).

**Comment by Drugoy** [comment]
Thank you!
